### ISSUE TITLE
Bot more than 1 person ?

### ISSUE THREAD

**Issue by hvhol** [jordenc/org.telegram.api.bot#1]
Is it possible that my partner can also receive de telegram messages ?
Its now send to a bot in Homey but only to me, is this possible?

**Comment by jordenc** [comment]
Not currently, but in the future it might be possible.

**Comment by Tweaqer** [comment]
I second this request, would be very handy!

**Comment by uNiiek** [comment]
Also I would be verry happy to send messages to other people in my contacts list with the TelegramBot.

**Comment by Veldkornet** [comment]
I suppose that this issue can now be closed? Since the bot can now be added to multiple persons as well as groups.
