### ISSUE TITLE
Fix/How to register if it is not registering

### ISSUE THREAD

**Issue by Tweaqer** [jordenc/org.telegram.api.bot#14]
I actually wanted to leave this in the review section, but I couldnt leave a review but I guess this might help people too.
If you are having issues with Homey not registering your device use the following way of installing the app:

0) Un-install the app (if you havent already) so it deletes all contents of the app
1) Install the app from the store
2) reboot Homey (this was actually the magic trick)
3) go to settings and insert your api key for the private bot and save that
4) click on 'apps' (or anywhere else as long as it points away from the telegram settings page)
5) go back to the settings page and you will no longer see the steps just the register command
6) copy-paste the register command in the chat of your telegram app ie. at web.telegram.org
7) check for the confirmation and try 'ping' if you will
8) Press the Donate button at https://apps.athom.com/app/org.telegram.api.bot
9) profit

**Comment by Fred0907** [comment]
Hi there, 
tried every step you wrote but still no reaction from Homey bot
Do you have other suggestions for help?

regards,

**Comment by Tweaqer** [comment]
You could try using the desktop/web interface of telegram instead of sending the register key via messenger, maybe you're missing a character via copy/paste or something else is going wrong. Other then that I'm drawing a blank
