### ISSUE TITLE
No respons by Homey bot

### ISSUE THREAD

**Issue by Fred0907** [jordenc/org.telegram.api.bot#15]
Hi Jorden,

Today i tried to register on homey bot, 
tried everything but got no respons from homey bot
even tried the solution from user Tweaqer but nothing happened.
Do you have any option or idea how to solve this?
thnx in advance

**Comment by Voxen1** [comment]
Similarly. Does not work.

**Comment by jordenc** [comment]
Are you both using the default Telegram bot, or did you make a custom one?

**Comment by Voxen1** [comment]
tried both options

**Comment by Fred0907** [comment]
I also tried both options

**Comment by jordenc** [comment]
Can you try to stop the Telegram app on Homey and start it again? That should trigger a disconnect, and reconnect to the Webhook of Athom. That could be the problem.

**Comment by Voxen1** [comment]
tried it. does not work ...(

**Comment by jordenc** [comment]
And you installed Telegram from the Athom app store and not from Github, right?

**Comment by Voxen1** [comment]
yes

**Comment by jordenc** [comment]
Did you copy the /register command correctly? Please make sure there are no additional spaces. Also, it is case sensitive.

If that's not the solution to the problem I don't really know what is....

**Comment by cab10** [comment]
Same problem here, does not work :(

**Comment by jordenc** [comment]
I think I found and solved this bug in version 0.2.8. It has been submitted to the appstore (but is pending approval)

Feel free to reopen this ticket if it doesn't work after updating.
