### ISSUE TITLE
Telegram with image grabber. 

### ISSUE THREAD

**Issue by robertb89** [jordenc/org.telegram.api.bot#17]
After getting a image I want to send it to my telegram. But when the picture will be send telegram stops working. Someone know how it will work again. It starts after updating to V2 from homey

**Comment by robertb89** [comment]
Select lokal image tag not the image grabber tag was the trick

**Comment by jordenc** [comment]
Did you use the tag that is on the "an image was grabbed"-card? Otherwise it might be an empty image and it could be that it didn't work.

**Comment by robertb89** [comment]
I'm sorry it's all ready done needed the image tag from local(homey) not the image tag from image grabber.
