### ISSUE TITLE
Cant get either easy or hard method to work after 3 tries

### ISSUE THREAD

**Issue by Desdichado** [jordenc/org.telegram.api.bot#18]
no response at all

**Comment by jordenc** [comment]
Can you try to restart the app? It could be that the app lost its connection to the Athom webhook.

**Comment by ON8SD** [comment]
I wasn't able to make the bot response either but the solution is very simple (eventually):
RIGHT BEFORE you type /register **code** you should restart the app (not Homey). Then all works fine. If you try to register first, then restart the app, it will not work anymore and you will have to reinstall the app.

I suggest a quick-fix by changing the 'howto' in the readme and on the settingspage?
Homey v1.5.3.

**Comment by pln8421** [comment]
I dont understand how to set up. I red the how to many times. 
Use telegram app? What app? Use Email @xxx?  Cannot be used because is not a valid address. Use link /register hgtFex4xxx? Where and how? Save button does not work?

**Comment by jordenc** [comment]
@pln8421 Try to restart the Telegram app on Homey if there is no response from the Homeybot. You send the "/register <code>" to Homeybot.

**Comment by jordenc** [comment]
I think I found and solved this bug in version 0.2.8. It has been submitted to the appstore (but is pending approval)

Feel free to reopen this ticket if it doesn't work after updating.
