### ISSUE TITLE
Register user creates duplicate user

### ISSUE THREAD

**Issue by MrBlue90** [jordenc/org.telegram.api.bot#19]
When registering a bot with several users and/or groups, I got an expensional amount of returns ("Homey is succesvol aan de Telegram chat gekoppeld") and users.
Where a total of 4 users/groups should be registered, I got about 20+ users listed in the settings (most duplicate)

**Comment by MrBlue90** [comment]
Additional info:
This happens with a custom bot.
First registration created 1 return/account, second 2, third 4, fourth 8, etc..

**Comment by jordenc** [comment]
Will have to look into this... not so easy to test, sadly.

**Comment by MrBlue90** [comment]
If you create a new bot and send the same register command from several user accounts, you will see this behavior.

**Comment by jordenc** [comment]
Will be updated in version 2.0.0 which will be released in a few days. Thanks for reporting!
