### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by FrankRinkens** [jordenc/org.telegram.api.bot#21]
Hi I won't to give a suggestion for improving Telegram functionality:

1) make it possible to send the value of a "Homey Logica" variable with Telegram
2) In a flow I grab an image from cam1 and in the next command grab an image from cam2. The "grabimage flow" sends the image with Telegram. Issue Telegram sends 2 times image from cam1. Think if the grabimage command is given twice they should run in sequence to avoid this.

Best regards,
Frank

**Comment by jordenc** [comment]
1. Could you explain this a little more... What do you mean with "Homey logica variable"?

2. If you use the local tags (drag them from the flowcard in Homey <= 1.5.13 or select the local tag in Homey 2.0+), it should work without a problem. I do this with 3 cams that I grab without a delay and never have any problems.

**Comment by FrankRinkens** [comment]
1) see that this is working, thought it was not possible to display a value of a Defined String.
2) didn't know to use the tags in 2.0, see it now. thx for explaining.
    I will test further with the 2 or even more cams, seems in a situation the image was overwritten? but maybe something else happend.

**Comment by jordenc** [comment]
2. The image tag in Homey itself can be "old" or "overwritten with the latest", so if you use that, results may vary :) the "local" image tag from the flowcard will be correct.

Will close this issue for now, don't hesitate to reopen if something still doesn't work!

**Comment by FrankRinkens** [comment]
What do you exactly mean by that?

I have 2 flows:

1) Flow name GrabImage **IF** This flow is started **THEN** Get image from Cam http://ip/cgi-bin/snapshot (do not login directly).

2) Flow name Send Image **IF** (image grabber: een afbeelding is opgehaald) **THEN** Telegram "Stuur een afbeelding" Image Grabber TAG

Is this how it is meant?

br Frank

**Comment by jordenc** [comment]
That is exactly how it should be

**Comment by FrankRinkens** [comment]
Ok thx, then I don't know where it went wrong. please close this issue.
