### ISSUE TITLE
Multiple messages

### ISSUE THREAD

**Issue by voord099** [jordenc/org.telegram.api.bot#22]
Since the Homey 2.0 update I keep getting triple or even quadruple messages from Homey in telegram

**Comment by jordenc** [comment]
That's weird. Can you try recreating the flows in Homey?

I'm on 2.0 and don't experience this on both my Homeys.

**Comment by voord099** [comment]
It occurs with both exciting (pre 2.0) and also with post 2.0 created flows. But all since the update, before that not problem at all

**Comment by jordenc** [comment]
I think you might have to delete the app and start over. Somewhere something must have gotten corrupted :(

**Comment by voord099** [comment]
I’ll give that a go tonight. Let you know

**Comment by jordenc** [comment]
I think this problem is solved now? If not, let me know.
