### ISSUE TITLE
Custom Bot Error: Finished

### ISSUE THREAD

**Issue by cab10** [jordenc/org.telegram.api.bot#24]
When I add they token it says
"Error: Finished"
on Telegram getwebhookinfo (I removed the hash):
{"ok":true,"result":{"url":"https://webhooks.athom.com/webhook/...hash...","has_custom_certificate":false,"pending_update_count":0,"max_connections":40}}
and webhookinfo
"ok":false,"error_code":404,"description":"Not Found: method not found"}

I have two Homeys in my account and that maybe the issue I guess?

**Comment by jordenc** [comment]
0.3.1 will probably fix the custom bot problems. It has been submitted to the appstore for approval.

**Comment by jordenc** [comment]
Please reopen this ticket if problems persist after the 3.0.1 update.
