### ISSUE TITLE
Can send but not receive Telegram messages

### ISSUE THREAD

**Issue by giggo** [jordenc/org.telegram.api.bot#27]
Hi
I can succesfully send messages to a Telegram user via the bot. I try to trigger a flow by receiving a telegram message but it doesn't work. Any idea how to figure out what is going wrong?
Ciao,
Gagga

**Comment by jordenc** [comment]
Did you follow the steps at the "Settings"-page, to register your Telegram user to the Homey bot?

Can you try restarting the Telegram app? Sometimes the webhook-connection seems to get disrupted.

**Comment by giggo** [comment]
Hm. I removed the app and started all over and can now receive messages too. Sorry for raising the issue before trying over again.

**Comment by MarcoBrood** [comment]
> Hi after the update yesterday same problem!

> I can succesfully send messages to a Telegram user via the bot. I try to trigger a flow by receiving a telegram message but it doesn't work. Any idea how to figure out what is going wrong?
> Ciao,
> Gagga

can
