### ISSUE TITLE
Not recieving updates after 0.3.0 update

### ISSUE THREAD

**Issue by Veldkornet** [jordenc/org.telegram.api.bot#29]
After the app updated to 0.3.0, my messages no longer send, although I don’t see any errors anywhere or anything. 

Telegram app: v0.3.0 - 24.05.19
Homey: 2.1.2

**Comment by Veldkornet** [comment]
I removed and reregistered everything with the normal Homey Bot (custom bot didn’t work and crashed the app). 

It registered the users and groups and I can see them in the settings. 

Problem is when I try to send messages via the flows, just nothing arrives.

**Comment by jordenc** [comment]
0.3.1 will probably fix the custom bot problems. It has been submitted to the appstore for approval.

I have a problem with the normal bot on my Homey-at-home. My office Homey works correctly though. It seems that the Telegram API has a stricter set of rules as of a few days or weeks. They are not allowing too many messages anymore. I am not sure yet, will have to investigate.
