### ISSUE TITLE
Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by jonkristian** [jordenc/org.telegram.api.bot#41]
Really love this app. Unfortunately it stopped working for me. Whenever i try to go into settings i get the following

 `Error: Cannot read property 'slice' of undefined`

I've tried wiping everything and re-installing but to no avail, running Homey 5.0.4.

**Comment by AdyRock** [comment]
I get the same error. It seems this function:
		function reverse_log() {
			
	        return this.log.slice().reverse();
	    
	    }
is the culprit. What is this.log mean to be as it is the only reference in the file?

**Comment by Joolee** [comment]
The whole function doesn't work right now. I guess the idea was to pull recent logs from Homey, reverse them and display them. But the whole pulling mechanism isn't implemented. You can remove the reference to renew_log from line 248 and the functionality would stay the same. New logs should still be added to the display so it's not completely broken. (Though I don't run the app so I can't test it)
https://github.com/jordenc/org.telegram.api.bot/blob/master/settings/index.html#L248

**Comment by jordenc** [comment]
The log field will be removed in the upcoming version, which will prevent the error.
