### ISSUE TITLE
New bot isn't responding to ping

### ISSUE THREAD

**Issue by rickerd** [jordenc/org.telegram.api.bot#5]
I added (twice) a new bot vi botfather and registered it in athomhomey_bot but.. it failed.
I did get a reponse or whatsoever.

**Comment by rnldnkp** [comment]
Same problem here

Solution:
1. walk trough the steps until the /register part
2. restart the Telegram Bot App
3. send the /register [code] to your own bot (not the general one)
4. You will get a response from homey! Now send Ping and you get Pong :)

**Comment by rickerd** [comment]
I guess the thing is to restart the app on Homey to get it all working *before* you register the bot in your own bot channel.
