### ISSUE TITLE
Cyrillic symbols in message

### ISSUE THREAD

**Issue by corsaroff** [jordenc/org.telegram.api.bot#6]
Hello. Great app! But can you add support for cyrillic symbols in message?

**Comment by Veldkornet** [comment]
Can maybe be resolved with something like urlencode?

https://stackoverflow.com/questions/41793311/cant-send-message-with-russian-symbols-with-telegram-bot

**Comment by LyoshaDovolen** [comment]
it works   https://github.com/jordenc/org.telegram.api.bot/pull/10

**Comment by corsaroff** [comment]
@jordenc Last update with Cyrillic symbols support is work. But my bot can't reply for my command - even basic command 'ping'. I installed back version from the Athom AppStore and it work again (without Cyrillic support, unfortunately).

**Comment by jordenc** [comment]
You are missing "secret" information that is not on Github. The new version was just approved and added to the store.
